env:
  browser: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-console: 0,
  import/extensions: 0,
  import/prefer-default-export: 0,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"]}],
  import/no-unresolved: 0,
  no-unused-vars: 0,
  no-shadow: 0,
  array-callback-return: 0,
  consistent-return: 0,
}
